    version: '3.9'
    
    services:
      postgres:
        image: postgres:17
        environment:
          POSTGRES_USER: ${DB_USERNAME}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          PGDATA: /data/postgres
          POSTGRES_DB: ${DB_NAME}
        volumes:
          - postgres_data:/data/postgres
        ports:
          - "5432:5432"
        networks:
          - postgres
        restart: unless-stopped
    
    networks:
      postgres:
        driver: bridge
    
    volumes:
        postgres_data: